[theme]
primaryColor = "#5f6ac4"          # El violeta de tus botones y enlaces
backgroundColor = "#0f172a"       # El fondo azul oscuro de tu HTML
secondaryBackgroundColor = "#1e293b" # El color de tus "cards"
textColor = "#e2e8f0"             # Gris claro de tu body
font = "sans serif"               # Streamlit usar√° una fuente similar a Inter
